## Sources App of Apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: dev-bootstrap-sources
    namespace: "argocd"
spec:
    project: default
    source:
        repoURL: 'https://github.com/Shubh-k04/hyperswitch-gitops'
        path: dev/sources
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
