## Sources App of Apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: dev-bootstrap-sources
    namespace: "argocd"
spec:
    project: default
    source:
        repoURL: 'https://github.com/Shubh-k04/hyperswitch-gitops.git'
        targetRevision: HEAD
        path: "dev/sources" # path to the application manifests
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: "argocd"
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
---

