apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hyperswitch-stack-rollouts
  namespace: argocd
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: hyperswitch-server
  template:
    metadata:
      labels:
        app: hyperswitch-server
  strategy:
    canary:
        maxSurge: 1
        maxUnavailable: 1